import React from "react"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
}

// This MUST be default exported
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
